[project]
name = "tordb"
version = "0.1.0"
description = "torrent db for parsing and serving movie torrents"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cinemagoer>=2023.5.1",
    "fastapi>=0.116.1",
    "loguru>=0.7.3",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
    "sqlalchemy>=2.0.43",
    "tmdbv3api>=1.9.0",
    "tortitle>=0.1.2",
    "uvicorn[standard]>=0.35.0",
]
